---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Make sure libvirt is started
  service:
    name: "{{ libvirt_service_name }}"
    state: "started"

- name: Check the state of the default qemu save directory
  stat:
    path: "/var/lib/libvirt/qemu/save"
  until: _qemu_save_dir.stat.exists | bool
  retries: 5
  delay: 10
  register: _qemu_save_dir

- name: Check if the qemu save directory is empty
  command: 'ls -1A /var/lib/libvirt/qemu/save'
  changed_when: false
  register: _qemu_save_dir_contents

- name: Move the existing save directory to nova_libvirt_save_path
  command: "mv /var/lib/libvirt/qemu/save {{ nova_libvirt_save_path }}"
  when:
    - _qemu_save_dir.stat.isdir is defined
    - _qemu_save_dir.stat.isdir | bool
    - _qemu_save_dir_contents.stdout_lines | length == 0

- name: Create the new save directory
  file:
    path: "{{ nova_libvirt_save_path }}"
    state: directory

- name: Symlink qemu save dir to nova_libvirt_save_path
  file:
    src: "{{ nova_libvirt_save_path }}"
    dest: "/var/lib/libvirt/qemu/save"
    state: link
    owner: "{{ nova_qemu_user }}"
    group: "{{ nova_qemu_group }}"

# Note (odyssey4me):
# These python libraries have C bindings which tend to be very
# particular about the version of their companion packages.
# To ensure things run smoothly for stable releases, we opt to
# use the distro packages for these and symlink the appropriate
# library files and binding into the venv.

- name: Link guestfs into the venv
  file:
    src: "{{ item.name }}"
    dest: "{{ nova_bin | dirname }}/lib/python2.7/{{ item.name | basename }}"
    state: "{{ item.state }}"
    force: "yes"
  with_items:
    - { state: link, name: "/usr/lib/python2.7/dist-packages/libguestfsmod.so" }
    - { state: link, name: "/usr/lib/python2.7/dist-packages/guestfs.py" }
  tags:
    - nova-install
    - nova-pip-packages

- name: Register libvirt module path
  command: python -c 'import libvirt; print libvirt.__file__'
  changed_when: false
  register: _libvirt_module_path
  tags:
    - nova-pip-packages

- name: Register libvirt-python files
  shell: >-
    {{ (ansible_pkg_mgr == 'apt') | ternary('dpkg -L python-libvirt', 'rpm -ql libvirt-python') }}
    | grep '^{{ _libvirt_module_path.stdout | dirname }}/'
  args:
    warn: no
  changed_when: false
  register: _libvirt_python_files
  tags:
    - nova-pip-packages

- name: Link the libvirt files into venv
  file:
    src: "{{ item }}"
    dest: "{{ nova_bin | dirname }}/lib/python2.7/site-packages/{{ item | basename }}"
    state: link
    force: yes
  with_items: "{{ _libvirt_python_files.stdout_lines }}"
  tags:
    - nova-pip-packages
